# Generated by Django 4.2.3 on 2023-07-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.IntegerField(default=0)),
                ("pnl", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(name="Player",),
    ]
