# Generated by Django 4.2.3 on 2023-07-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_aiplayer_trade_player"),
    ]

    operations = [
        migrations.RemoveField(model_name="trader", name="position",),
    ]
