# Generated by Django 4.2.3 on 2023-07-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0004_remove_trader_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="quantity",
            field=models.IntegerField(default=2000),
        ),
    ]
