# Generated by Django 4.2.3 on 2023-07-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0005_trade_quantity"),
    ]

    operations = [
        migrations.RemoveField(model_name="trader", name="pnl",),
    ]
