# Generated by Django 4.2.3 on 2023-07-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0006_remove_trader_pnl"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="pnl",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
