# Generated by Django 4.2.3 on 2023-07-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0007_trade_pnl"),
    ]

    operations = [
        migrations.RemoveField(model_name="trade", name="pnl",),
    ]
