# Generated by Django 4.2.3 on 2023-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0008_remove_trade_pnl"),
    ]

    operations = [
        migrations.AddField(
            model_name="player", name="position", field=models.IntegerField(default=0),
        ),
    ]
