# Generated by Django 4.2.3 on 2023-07-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0009_player_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="cash_flow",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
