# Generated by Django 4.0.6 on 2023-08-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_player_cash_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiplayer',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='aiplayer',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
