# Generated by Django 4.0.6 on 2023-08-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_aiplayer_bid_aiplayer_offer_player_bid_player_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trade_out_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('players', models.ManyToManyField(to='trading.player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.gamesession')),
            ],
        ),
        migrations.AddField(
            model_name='aiplayer',
            name='games',
            field=models.ManyToManyField(related_name='ai_players', to='trading.gamesession'),
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(related_name='human_players', to='trading.gamesession'),
        ),
        migrations.AddField(
            model_name='trade',
            name='game_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.gamesession'),
        ),
    ]
