# Generated by Django 4.0.6 on 2023-08-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_gamesession_round_aiplayer_games_player_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.IntegerField(default=0),
        ),
    ]
