# Generated by Django 4.0.6 on 2023-08-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_round_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.gamesession'),
        ),
    ]
