# Generated by Django 4.0.6 on 2023-08-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_alter_trade_game_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiplayer',
            name='games',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ai_players',
            field=models.ManyToManyField(related_name='game_sessions', to='trading.aiplayer'),
        ),
    ]
