# Generated by Django 4.0.6 on 2023-08-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_remove_aiplayer_games_gamesession_ai_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(related_name='games', to='trading.gamesession'),
        ),
    ]
