# Generated by Django 4.2.4 on 2023-09-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0016_alter_player_games"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                (
                    "impact_type",
                    models.CharField(
                        choices=[("bullish", "Bullish"), ("bearish", "Bearish")],
                        max_length=7,
                    ),
                ),
                ("impact_value", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
