# Generated by Django 4.2.4 on 2023-09-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0019_aiplayer_current_ev"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="release_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
